// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIyKdtH6FeOaI3I3XZ8vtwECLATnwy7Sw',
    appId: '1:540290890159:web:8f7d6c5b4a3e2f1a04175a',
    messagingSenderId: '540290890159',
    projectId: 'trueastrotalk-1',
    authDomain: 'trueastrotalk-1.firebaseapp.com',
    storageBucket: 'trueastrotalk-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIyKdtH6FeOaI3I3XZ8vtwECLATnwy7Sw',
    appId: '1:540290890159:android:2b9e8d7c6f5a4e3d04175a',
    messagingSenderId: '540290890159',
    projectId: 'trueastrotalk-1',
    storageBucket: 'trueastrotalk-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIyKdtH6FeOaI3I3XZ8vtwECLATnwy7Sw',
    appId: '1:540290890159:ios:e889c01ea401aa4904175a',
    messagingSenderId: '540290890159',
    projectId: 'trueastrotalk-1',
    storageBucket: 'trueastrotalk-1.firebasestorage.app',
    iosBundleId: 'com.trueastrotalk.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIyKdtH6FeOaI3I3XZ8vtwECLATnwy7Sw',
    appId: '1:540290890159:ios:e889c01ea401aa4904175a',
    messagingSenderId: '540290890159',
    projectId: 'trueastrotalk-1',
    storageBucket: 'trueastrotalk-1.firebasestorage.app',
    iosBundleId: 'com.trueastrotalk.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIyKdtH6FeOaI3I3XZ8vtwECLATnwy7Sw',
    appId: '1:540290890159:web:8f7d6c5b4a3e2f1a04175a',
    messagingSenderId: '540290890159',
    projectId: 'trueastrotalk-1',
    authDomain: 'trueastrotalk-1.firebaseapp.com',
    storageBucket: 'trueastrotalk-1.firebasestorage.app',
  );
}